---
- name: configure celery and celery beat
  template: src=celery.conf
            dest=/etc/supervisor/conf.d/{{ project_name }}-celery-{{ item.name }}.conf
            owner=root
            group=root
            mode=0600
  with_items:
    - { name: "default", command: "worker", flags: "{{ celery_worker_extra_args|default('--loglevel=INFO') }}" }
    - { name: "beat", command: "beat", flags: "--schedule={{ root_dir }}/celerybeat-schedule.db --pidfile={{ root_dir }}/celerybeat.pid --loglevel=INFO" }
  notify:
    - reread supervisor managed app files
    - restart supervisor managed apps that updated confs
    - ensure celery is running
