---
- name: configure celery and celery beat
  template: src=celery.conf
            dest=/etc/supervisor/conf.d/{{ project_name }}-celery-{{ item.name }}.conf
            owner=root
            group=root
            mode=0600
  with_items:
    - { name: "default", command: "worker", flags: "--loglevel=INFO" }
    - { name: "beat", command: "beat", flags: "--schedule={{ root_dir }}/celerybeat-schedule.db --pidfile={{ root_dir }}/celerybeat.pid --loglevel=INFO" }
  register: celery_conf

- name: restart celery when the conf has changed
  supervisorctl: name={{ project_name }}-celery-{{ item }} state=restarted
  with_items:
    - default
    - beat
  when: celery_conf|changed

- name: ensure celery is running
  supervisorctl: name={{ project_name }}-celery-{{ item }} state=started
  with_items:
    - default
    - beat
