---
- name: npm install packages
  npm: path={{ source_dir }} state=latest
  become_user: "{{ project_user }}"

- name: npm run build
  command: npm run build
  args:
    chdir: "{{ source_dir }}"
  become_user: "{{ project_user }}"

- name: install less
  npm: name=less version={{ less_version }} state=present

# In order to allow gunicorn to find it.  See https://github.com/caktus/margarita/issues/75.
- name: symlink less
  file: src=/usr/local/bin/lessc
        dest=/usr/bin/lessc
        state=link
