---
- name: npm install packages
  npm: path={{ source_dir }} state=latest
  become_user: "{{ project_user }}"

- name: npm run build
  command: npm run build
  args:
    chdir: "{{ source_dir }}"
  become_user: "{{ project_user }}"
