---
- name: Nginx PPA
  apt_repository: repo="ppa:nginx/stable" state=present

- name: install nginx
  apt: name=nginx
       state=present

- name: start nginx
  service: name=nginx
           state=restarted

- name: edit nginx.conf
  lineinfile: dest=/etc/nginx/nginx.conf
              regexp=" server_names_hash_bucket_size 64;"
              insertafter="^# server_names_hash_bucket_size 64;"
              line="        server_names_hash_bucket_size 64;"

- name: remove_existing_conf
  file: path=/etc/nginx/sites-enabled/default
        state=absent
