---
- name: collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ source_dir }}"
    virtualenv: "{{ venv_dir }}"
  become_user: "{{ project_user }}"
  vars:
    ansible_ssh_pipelining: true
