---
- name: chown node_modules
  file:
    owner: "{{ project_user }}"
    group: "{{ project_user }}"
    path: "{{ source_dir }}/node_modules"
    recurse: yes

- name: npm run build
  command: npm run build
  args:
    chdir: "{{ source_dir }}"
  become_user: "{{ project_user }}"
  vars:
    ansible_ssh_pipelining: true

- name: collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ source_dir }}"
    virtualenv: "{{ venv_dir }}"
  become_user: "{{ project_user }}"
  vars:
    ansible_ssh_pipelining: true
