---
- name: install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql-contrib-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - libpq-dev
    - postgresql-{{ pg_version }}
    - python-psycopg2

- name: remove the postgres meta-package
  apt: name=postgresql state=absent

- name: ensure postgres is running
  service: name=postgres state=started

# The postgres < 9.3 problem with the default encoding not being utf8
# isn't a problem with Ansible >= 1.6.  Hopefully.
# ref: https://github.com/ansible/ansible/issues/7246

- name: create the project postgres user
  postgresql_user: name="{{ project_name }}_{{ environment }}"
                   role_attr_flags=NOCREATEDB,NOCREATEROLE,NOCREATESUPERUSER
                   password="{{ db_password }}"
                   encrypted=yes

- name: create the project database
  postgresql_db: name="{{ project_name }}_{{ environment }}"
                 owner="{{ project_name }}_{{ environment }}"
                 state=present
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
