---
# file: tequila/deploy.yml
#
# This playbook will deploy an entire environment
#
- hosts: all
  pre_tasks:
    - name: apt update
      apt: update_cache=yes
  roles:
    - common

- hosts: db
  roles:
    - db-master

- hosts: worker
  roles:
    - worker

- hosts: web
  roles:
    - balancer
    - web

- hosts: cache
  roles:
    - cache

- hosts: queue
  roles:
    - queue

- hosts: worker
  roles:
    - worker
