---
# file: tequila/deploy.yml
#
# This playbook will deploy the entire environment
#
- hosts: all
  pre_tasks:
    - name: apt update
      apt: update_cache=yes
  roles:
    - common

- hosts: db
  roles:
    - db-master

- hosts: worker
  roles:
    - worker

- hosts: web
  roles:
    - web
