---
- name: install base packages
  apt: pkg={{ item }} state=present
  with_items:
    - python-software-properties
    - dpkg-dev
    - wget
    - build-essential
    - vim
    - byobu
    - ntp
    - sudo
    - ufw
    - fail2ban
    - openssh-client
    - openssh-server

- name: ensure that the admin and login groups are present
  group: name={{ item }} state=present system=yes
  with_items:
    - admin
    - login

- name: allow admin group users to sudo
  copy: src=admin dest=/etc/sudoers.d/admin owner=root mode=0440

- name: allow ssh through firewall
  ufw: rule=allow port=ssh

- name: ensure ufw is turned on
  ufw: state=enabled policy=deny

- name: ensure fail2ban is turned on
  service: name=fail2ban state=enabled

- name: configure fail2ban
  copy: src=jail.local dest=/etc/fail2ban/jail.local owner=root mode=0644
  notify:
    - restart fail2ban

- name: configure sshd
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root mode=0644
  notify:
    - restart sshd

- name: add github to the ssh known hosts
  known_hosts: path=/etc/ssh/ssh_known_hosts
               host=github.com
               state=present
               key="{{ lookup('file', 'github.pub') }}"

- name: set the locale to utf8
  lineinfile: line={{ item }} state=present create=yes owner=root mode=0644
  with_items:
    - "LC_ALL=en_US.UTF-8"
    - "LANG=en_US.UTF-8"
