---
- name: add the deadsnakes ppa
  apt_repository: repo="ppa:fkrull/deadsnakes" state=present

- name: install app packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - python-pip
    - libpq-dev
    - libev-dev
    - libevent-dev
    - libmemcached-dev
    - libjpeg8
    - libjpeg8-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g
    - zlib1g-dev
    - libxml2-dev
    - libxslt1-dev
    - ghostscript
    - libpython{{ python_version }}
    - libpython{{ python_version }}-dev
    - python{{ python_version }}
    - python{{ python_version }}-dev
    - postfix
    - git-core

- name: ensure postfix is running
  service: name=postfix state=started

# TODO: pip install supervisord and set up

- name: upload github key
  copy: content={{ github_deploy_key }}
        dest={{ ssh_dir }}/github
        owner={{ project_name }}
        group={{ project_name }}
        mode=600
  register: github_key
  when: github_deploy_key is defined

- name: rsync project source to /vagrant/
  synchronize: >-
    src={{ source_dir }}
    dest=/vagrant/
    recursive=yes
    delete=yes
  when: env_name == 'local'

- name: checkout latest project source
  git: repo={{ repo.url }}
       dest={{ source_dir }}
       version={{ repo.branch|default('master') }}
       force=yes
       key_file={{ github_key.dest|default(None) }}
  remote_user: "{{ project_name }}"
  when: env_name != 'local'

- name: delete pyc files
  shell: find . -name '*.pyc' -delete

- name: pip install the project requirements
  pip: requirements={{ root_dir }}/requirements/{{ requirements_name[env_name]|default('production') }}.txt
       virtualenv={{ venv_dir }}
       virtualenv_python=/usr/bin/python{{ python_version }}
  remote_user: "{{ project_name }}"

- name: set up the project python path
  copy: content="{{ source_dir }}"
        dest={{ venv_dir }}/lib/python{{ python_version }}/site-packages/project.pth
        user={{ project_name }}
        group={{ project_name }}

# TODO: copy over environment variables to be used with the project
